name: 'test'
description: 'execute tests'
runs:
  using: "composite"

  strategy:
    fail-fast: true
    matrix:
      node-version: ["12.22.6", "14.x", "16.x"]

  steps:
    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://registry.npmjs.org/"

    # https://github.com/pnpm/action-setup
    - name: cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    # https://github.com/pnpm/action-setup
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.x
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: test
      run: pnpm run test