# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ["12.22.6", "14.x", "16.x"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"
      - run: npm i -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test
      - run: pnpm run build
